development:
  adapter: postgresql
  encoding: unicode
  database: headhunt_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: headhunt_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: headhunt_prod
  pool: 5
  host: localhost

